!$NB_AZURE_PLANTUML_DIS = "https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist"
' --- AIMachineLearning ----

!$AzureBatchAI = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureBatchAI.png"
!$AzureBotService = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureBotService.png"
!$AzureCognitiveServices = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureCognitiveServices.png"
!$AzureMachineLearningService = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureMachineLearningService.png"
!$AzureMachineLearningStudio = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureMachineLearningStudio.png"
!$AzureMachineLearningStudioClassic = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureMachineLearningStudioClassic.png"
!$AzureMachineLearningStudioWebServicePlan = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureMachineLearningStudioWebServicePlan.png"
!$AzureMachineLearningStudioWorkspace = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureMachineLearningStudioWorkspace.png"
!$AzureTranslatorText = $NB_AZURE_PLANTUML_DIS + "/AIMachineLearning/AzureTranslatorText.png"

' --- Databases ----

!$AzureCosmosDb = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureCosmosDb.png"
!$AzureDatabaseForMariaDB = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDatabaseForMariaDB.png"
!$AzureDatabaseForMySQL = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDatabaseForMySQL.png"
!$AzureDatabaseForPostgreSQL = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDatabaseForPostgreSQL.png"
!$AzureDatabaseMigrationService = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDatabaseMigrationService.png"
!$AzureDataBricks = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDataBricks.png"
!$AzureDataExplorerCluster = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDataExplorerCluster.png"
!$AzureDataFactory = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureDataFactory.png"
!$AzureInstancePool = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureInstancePool.png"
!$AzureManagedDatabase = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureManagedDatabase.png"
!$AzureRedisCache = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureRedisCache.png"
!$AzureSql = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSql.png"
!$AzureSqlDatabase = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlDatabase.png"
!$AzureSqlDataWarehouse = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlDataWarehouse.png"
!$AzureSqlElasticPool = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlElasticPool.png"
!$AzureSqlManagedInstance = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlManagedInstance.png"
!$AzureSqlServer = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlServer.png"
!$AzureSqlStretchDatabase = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlStretchDatabase.png"
!$AzureSqlVirtualMachine = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSqlVirtualMachine.png"
!$AzureSSISLiftAndShift = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureSSISLiftAndShift.png"
!$AzureVirtualCluster = $NB_AZURE_PLANTUML_DIS + "/Databases/AzureVirtualCluster.png"

' --- Copute ----

!$AzureAppService = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureAppService.png"
!$AzureAppServicePlan = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureAppServicePlan.png"
!$AzureAppServicePlanLinux = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureAppServicePlanLinux.png"
!$AzureAutomanagedVirtualMachine = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureAutomanagedVirtualMachine.png"
!$AzureAvailabiltySet = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureAvailabiltySet.png"
!$AzureBatch = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureBatch.png"
!$AzureBatchAccount = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureBatchAccount.png"
!$AzureCloudServices = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureCloudServices.png"
!$AzureContainerService = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureContainerService.png"
!$AzureDisk = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureDisk.png"
!$AzureDiskEncryptionSet = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureDiskEncryptionSet.png"
!$AzureDiskSnapshot = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureDiskSnapshot.png"
!$AzureFunction = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureFunction.png"
!$AzureImageClassic = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureImageClassic.png"
!$AzureImageDefinition = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureImageDefinition.png"
!$AzureImageVersion = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureImageVersion.png"
!$AzureMeshApplication = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureMeshApplication.png"
!$AzureServerFarm = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureServerFarm.png"
!$AzureServiceFabric = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureServiceFabric.png"
!$AzureSharedImageGallery = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureSharedImageGallery.png"
!$AzureSpringCloud = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureSpringCloud.png"
!$AzureVirtualDesktop = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualDesktop.png"
!$AzureVirtualDesktopApplicationGroup = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualDesktopApplicationGroup.png"
!$AzureVirtualDesktopHostPool = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualDesktopHostPool.png"
!$AzureVirtualDesktopWorkspace = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualDesktopWorkspace.png"
!$AzureVirtualMachine = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualMachine.png"
!$AzureVirtualMachineClassic = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualMachineClassic.png"
!$AzureVirtualMachineScaleSet = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureVirtualMachineScaleSet.png"
!$AzureWebSlot = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureWebSlot.png"
!$AzureWebTest = $NB_AZURE_PLANTUML_DIS + "/Compute/AzureWebTest.png"

' --- Container ----

!$AzureContainerApp = $NB_AZURE_PLANTUML_DIS + "/Containers/AzureContainerApp.png"
!$AzureContainerInstance = $NB_AZURE_PLANTUML_DIS + "/Containers/AzureContainerInstance.png"
!$AzureContainerRegistry = $NB_AZURE_PLANTUML_DIS + "/Containers/AzureContainerRegistry.png"
!$AzureKubernetesService = $NB_AZURE_PLANTUML_DIS + "/Containers/AzureKubernetesService.png"
!$AzureServiceEnvironment = $NB_AZURE_PLANTUML_DIS + "/Containers/AzureServiceEnvironment.png"

' --- Ceneral ----

!$Azure = $NB_AZURE_PLANTUML_DIS + "/General/Azure.png"
!$AzureWorkbook = $NB_AZURE_PLANTUML_DIS + "/General/AzureWorkbook.png"
!$AzureWorkflow = $NB_AZURE_PLANTUML_DIS + "/General/AzureWorkflow.png"

' --- Identity ----
!$AzureActiveDirectory = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectory.png"
!$AzureActiveDirectoryB2C = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryB2C.png"
!$AzureActiveDirectoryConnectHealth = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryConnectHealth.png"
!$AzureActiveDirectoryDomainServices = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryDomainServices.png"
!$AzureActiveDirectoryGroup = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryGroup.png"
!$AzureActiveDirectoryIdentityProtection = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryIdentityProtection.png"
!$AzureActiveDirectoryRolesAndAdministrators = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryRolesAndAdministrators.png"
!$AzureActiveDirectoryUser = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureActiveDirectoryUser.png"
!$AzureAppRegistration = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureAppRegistration.png"
!$AzureEnterpriseApplication = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureEnterpriseApplication.png"
!$AzureIdentityGovernance = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureIdentityGovernance.png"
!$AzureManagedIdentity = $NB_AZURE_PLANTUML_DIS + "/Identity/AzureManagedIdentity.png"

' --- Networking ----
!$AzureApplicationGateway = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureApplicationGatewa.png"
!$AzureAzureDDoSProtection = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureAzureDDoSProtectio.png"
!$AzureBastion = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureBastio.png"
!$AzureCDNProfile = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureCDNProfil.png"
!$AzureDNS = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureDN.png"
!$AzureDNSServer = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureDNSServe.png"
!$AzureExpressRoute = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureExpressRout.png"
!$AzureExpressRouteCircuit = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureExpressRouteCircui.png"
!$AzureExpressRouteDirect = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureExpressRouteDirec.png"
!$AzureFirewall = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureFirewal.png"
!$AzureFirewallManager = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureFirewallManage.png"
!$AzureFrontDoor = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureFrontDoo.png"
!$AzureFrontDoorService = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureFrontDoorServic.png"
!$AzureIPAddressSpace = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureIPAddressSpac.png"
!$AzureIPGroup = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureIPGroup.png"
!$AzureLoadBalancer = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureLoadBalance.png"
!$AzureNAT = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureNA.png"
!$AzureNetworkInterface = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureNetworkInterfac.png"
!$AzureNSG = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureNS.png"
!$AzurePrivateLink = $NB_AZURE_PLANTUML_DIS + "/Networking/AzurePrivateLin.png"
!$AzurePrivateLinkHub = $NB_AZURE_PLANTUML_DIS + "/Networking/AzurePrivateLinkHu.png"
!$AzurePrivateLinkService = $NB_AZURE_PLANTUML_DIS + "/Networking/AzurePrivateLinkServic.png"
!$AzurePublicIPAddress = $NB_AZURE_PLANTUML_DIS + "/Networking/AzurePublicIPAddres.png"
!$AzurePublicIPAddressClassic = $NB_AZURE_PLANTUML_DIS + "/Networking/AzurePublicIPAddressClassi.png"
!$AzurePublicIPPrefix = $NB_AZURE_PLANTUML_DIS + "/Networking/AzurePublicIPPrefi.png"
!$AzureRouteFilter = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureRouteFilte.png"
!$AzureRouteTable = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureRouteTabl.png"
!$AzureServiceEndpoint = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureServiceEndpoin.png"
!$AzureServiceEndpointPolicy = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureServiceEndpointPolic.png"
!$AzureSubnet = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureSubne.png"
!$AzureTrafficManager = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureTrafficManager.png"
!$AzureVirtualNetwork = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureVirtualNetwor.png"
!$AzureVirtualNetworkPeering = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureVirtualNetworkPeerin.png"
!$AzureVirtualWAN = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureVirtualWA.png"
!$AzureVPNGateway = $NB_AZURE_PLANTUML_DIS + "/Networking/AzureVPNGatewa.png"
