' Styling
' ##################################

hide stereotype

!definelong AzureEntityColoring(e_stereo)
skinparam rectangle<<e_stereo>> {
    BackgroundColor AZURE_BG_COLOR
    BorderColor transparent
    Shadowing false
}
!enddefinelong

!define AZURE_PNG_ICON_SCALE = '0.5'

' Overwriting Elements
' ##################################

!definelong AzureEntity(e_alias, e_label, e_techn, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><img:https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/diste_sprite.png{scale=AZURE_PNG_ICON_SCALE}></color>\n\n==e_label" <<e_stereo>> as e_alias
!enddefinelong

!definelong AzureEntity(e_alias, e_label, e_techn, e_descr, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><img:https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/diste_sprite.png{scale=AZURE_PNG_ICON_SCALE}></color>\n\n==e_label" <<e_stereo>> as e_alias
!enddefinelong
