
' --- AIMachineLearning ----

!define AzureBatchAI_png = '/AIMachineLearning/AzureBatchAI.png'
!define AzureBotService_png = '/AIMachineLearning/AzureBotService.png'
!define AzureCognitiveServices_png = '/AIMachineLearning/AzureCognitiveServices.png'
!define AzureMachineLearningService_png = '/AIMachineLearning/AzureMachineLearningService.png'
!define AzureMachineLearningStudio_png = '/AIMachineLearning/AzureMachineLearningStudio.png'
!define AzureMachineLearningStudioClassic_png = '/AIMachineLearning/AzureMachineLearningStudioClassic.png'
!define AzureMachineLearningStudioWebServicePlan_png = '/AIMachineLearning/AzureMachineLearningStudioWebServicePlan.png'
!define AzureMachineLearningStudioWorkspace_png = '/AIMachineLearning/AzureMachineLearningStudioWorkspace.png'
!define AzureTranslatorText_png = '/AIMachineLearning/AzureTranslatorText.png'

' --- Databases ----

AzureCosmosDb_png = '/Databases/AzureCosmosDb.png'
AzureDatabaseForMariaDB_png = '/Databases/AzureDatabaseForMariaDB.png'
AzureDatabaseForMySQL_png = '/Databases/AzureDatabaseForMySQL.png'
AzureDatabaseForPostgreSQL_png = '/Databases/AzureDatabaseForPostgreSQL.png'
AzureDatabaseMigrationService_png = '/Databases/AzureDatabaseMigrationService.png'
AzureDataBricks_png = '/Databases/AzureDataBricks.png'
AzureDataExplorerCluster_png = '/Databases/AzureDataExplorerCluster.png'
AzureDataFactory_png = '/Databases/AzureDataFactory.png'
AzureInstancePool_png = '/Databases/AzureInstancePool.png'
AzureManagedDatabase_png = '/Databases/AzureManagedDatabase.png'
AzureRedisCache_png = '/Databases/AzureRedisCache.png'
AzureSql_png = '/Databases/AzureSql.png'
AzureSqlDatabase_png = '/Databases/AzureSqlDatabase.png'
AzureSqlDataWarehouse_png = '/Databases/AzureSqlDataWarehouse.png'
AzureSqlElasticPool_png = '/Databases/AzureSqlElasticPool.png'
AzureSqlManagedInstance_png = '/Databases/AzureSqlManagedInstance.png'
AzureSqlServer_png = '/Databases/AzureSqlServer.png'
AzureSqlStretchDatabase_png = '/Databases/AzureSqlStretchDatabase.png'
AzureSqlVirtualMachine_png = '/Databases/AzureSqlVirtualMachine.png'
AzureSSISLiftAndShift_png = '/Databases/AzureSSISLiftAndShift.png'
AzureVirtualCluster_png = '/Databases/AzureVirtualCluster.png'

' --- Copute ----

AzureAppService_png = '/Compute/AzureAppService.png'
AzureAppServicePlan_png = '/Compute/AzureAppServicePlan.png'
AzureAppServicePlanLinux_png = '/Compute/AzureAppServicePlanLinux.png'
AzureAutomanagedVirtualMachine_png = '/Compute/AzureAutomanagedVirtualMachine.png'
AzureAvailabiltySet_png = '/Compute/AzureAvailabiltySet.png'
AzureBatch_png = '/Compute/AzureBatch.png'
AzureBatchAccount_png = '/Compute/AzureBatchAccount.png'
AzureCloudServices_png = '/Compute/AzureCloudServices.png'
AzureContainerService_png = '/Compute/AzureContainerService.png'
AzureDisk_png = '/Compute/AzureDisk.png'
AzureDiskEncryptionSet_png = '/Compute/AzureDiskEncryptionSet.png'
AzureDiskSnapshot_png = '/Compute/AzureDiskSnapshot.png'
AzureFunction_png = '/Compute/AzureFunction.png'
AzureImageClassic_png = '/Compute/AzureImageClassic.png'
AzureImageDefinition_png = '/Compute/AzureImageDefinition.png'
AzureImageVersion_png = '/Compute/AzureImageVersion.png'
AzureMeshApplication_png = '/Compute/AzureMeshApplication.png'
AzureServerFarm_png = '/Compute/AzureServerFarm.png'
AzureServiceFabric_png = '/Compute/AzureServiceFabric.png'
AzureSharedImageGallery_png = '/Compute/AzureSharedImageGallery.png'
AzureSpringCloud_png = '/Compute/AzureSpringCloud.png'
AzureVirtualDesktop_png = '/Compute/AzureVirtualDesktop.png'
AzureVirtualDesktopApplicationGroup_png = '/Compute/AzureVirtualDesktopApplicationGroup.png'
AzureVirtualDesktopHostPool_png = '/Compute/AzureVirtualDesktopHostPool.png'
AzureVirtualDesktopWorkspace_png = '/Compute/AzureVirtualDesktopWorkspace.png'
AzureVirtualMachine_png = '/Compute/AzureVirtualMachine.png'
AzureVirtualMachineClassic_png = '/Compute/AzureVirtualMachineClassic.png'
AzureVirtualMachineScaleSet_png = '/Compute/AzureVirtualMachineScaleSet.png'
AzureWebSlot_png = '/Compute/AzureWebSlot.png'
AzureWebTest_png = '/Compute/AzureWebTest.png'

'--- Container ----

AzureContainerApp_png = '/Containers/AzureContainerApp.png'
AzureContainerInstance_png = '/Containers/AzureContainerInstance.png'
AzureContainerRegistry_png = '/Containers/AzureContainerRegistry.png'
AzureKubernetesService_png = '/Containers/AzureKubernetesService.png'
AzureServiceEnvironment_png = '/Containers/AzureServiceEnvironment.png'

'--- Ceneral ----

Azure_png = '/General/Azure.png'
AzureWorkbook_png = '/General/AzureWorkbook.png'
AzureWorkflow_png = '/General/AzureWorkflow.png'

'--- Identity ----
AzureActiveDirectory_png = '/Identity/AzureActiveDirectory.png'
AzureActiveDirectoryB2C_png = '/Identity/AzureActiveDirectoryB2C.png'
AzureActiveDirectoryConnectHealth_png = '/Identity/AzureActiveDirectoryConnectHealth.png'
AzureActiveDirectoryDomainServices_png = '/Identity/AzureActiveDirectoryDomainServices.png'
AzureActiveDirectoryGroup_png = '/Identity/AzureActiveDirectoryGroup.png'
AzureActiveDirectoryIdentityProtection_png = '/Identity/AzureActiveDirectoryIdentityProtection.png'
AzureActiveDirectoryRolesAndAdministrators_png = '/Identity/AzureActiveDirectoryRolesAndAdministrators.png'
AzureActiveDirectoryUser_png = '/Identity/AzureActiveDirectoryUser.png'
AzureAppRegistration_png = '/Identity/AzureAppRegistration.png'
AzureEnterpriseApplication_png = '/Identity/AzureEnterpriseApplication.png'
AzureIdentityGovernance_png = '/Identity/AzureIdentityGovernance.png'
AzureManagedIdentity_png = '/Identity/AzureManagedIdentity.png'

' --- Networking ----
AzureApplicationGatewa_png = '/Networking/AzureApplicationGatewa.png'
AzureAzureDDoSProtectio_png = '/Networking/AzureAzureDDoSProtectio.png'
AzureBastio_png = '/Networking/AzureBastio.png'
AzureCDNProfil_png = '/Networking/AzureCDNProfil.png'
AzureDN_png = '/Networking/AzureDN.png'
AzureDNSServe_png = '/Networking/AzureDNSServe.png'
AzureExpressRout_png = '/Networking/AzureExpressRout.png'
AzureExpressRouteCircui_png = '/Networking/AzureExpressRouteCircui.png'
AzureExpressRouteDirec_png = '/Networking/AzureExpressRouteDirec.png'
AzureFirewal_png = '/Networking/AzureFirewal.png'
AzureFirewallManage_png = '/Networking/AzureFirewallManage.png'
AzureFrontDoo_png = '/Networking/AzureFrontDoo.png'
AzureFrontDoorServic_png = '/Networking/AzureFrontDoorServic.png'
AzureIPAddressSpac_png = '/Networking/AzureIPAddressSpac.png'
AzureIPGroup_png = '/Networking/AzureIPGroup.png'
AzureLoadBalance_png = '/Networking/AzureLoadBalance.png'
AzureNA_png = '/Networking/AzureNA.png'
AzureNetworkInterfac_png = '/Networking/AzureNetworkInterfac.png'
AzureNS_png = '/Networking/AzureNS.png'
AzurePrivateLin_png = '/Networking/AzurePrivateLin.png'
AzurePrivateLinkHu_png = '/Networking/AzurePrivateLinkHu.png'
AzurePrivateLinkServic_png = '/Networking/AzurePrivateLinkServic.png'
AzurePublicIPAddres_png = '/Networking/AzurePublicIPAddres.png'
AzurePublicIPAddressClassi_png = '/Networking/AzurePublicIPAddressClassi.png'
AzurePublicIPPrefi_png = '/Networking/AzurePublicIPPrefi.png'
AzureRouteFilte_png = '/Networking/AzureRouteFilte.png'
AzureRouteTabl_png = '/Networking/AzureRouteTabl.png'
AzureServiceEndpoin_png = '/Networking/AzureServiceEndpoin.png'
AzureServiceEndpointPolic_png = '/Networking/AzureServiceEndpointPolic.png'
AzureSubne_png = '/Networking/AzureSubne.png'
AzureTrafficManage_png = '/Networking/AzureTrafficManage.png'
AzureVirtualNetwor_png = '/Networking/AzureVirtualNetwor.png'
AzureVirtualNetworkPeerin_png = '/Networking/AzureVirtualNetworkPeerin.png'
AzureVirtualWA_png = '/Networking/AzureVirtualWA.png'
AzureVPNGatewa_png = '/Networking/AzureVPNGatewa.png'

