!define NB_ICON_SCALE 1

skinparam rectangle<<NBIcon>> {
    BackgroundColor transparent
    BorderColor transparent
    Shadowing false
}

!definelong User_Monitor(e_alias, e_label)
rectangle "<img:https://raw.githubusercontent.com/nicobit/nb-plantuml/main/puml/images/Users/user_monitor.png{scale=NB_ICON_SCALE}>\ne_label\n" <<NBIcon>> as e_alias
!enddefinelong
